name: Unzip File in Repository

on:
  workflow_dispatch: # इसे मैन्युअली रन करने के लिए

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unzip File
        run: |
          unzip ak2.zip -d extracted_files
          ls -l extracted_files # फोल्डर चेक करने के लिए

      - name: Commit and Push Unzipped Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add extracted_files
          git commit -m "Unzipped files"
          git push
